[connections.supabase]
SUPABASE_URL = "https://pcfqzrzelgvutthbijzg.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZnF6cnplbGd2dXR0aGJpanpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDY4ODYsImV4cCI6MjA2ODE4Mjg4Nn0.zVUs0K7vNIUvwxJCesUsVhjpZn5vTm0VrCoiuVCo07k"
ABLY_API_KEY = "eeRj2w.SxEzww:V5fRxHSA9MIHZPxbUtpnP_34Y-1DUYI54D4SaQ3WtV8"  
